name: Hourly Data Collector

# This tells the robot when to run. 
# It runs on a schedule (every hour) and can also be run manually.
on:
  schedule:
    # Runs at the beginning of every hour.
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  collect-data:
    # The robot will use a standard, clean "Ubuntu" computer.
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install the necessary Python libraries.
      - name: Install dependencies
        run: pip install requests pandas

      # Step 4: Run your data collection script.
      # This will update the solar_data.csv file.
      - name: Run data collection script
        run: python fetch_data.py

      # Step 5: Automatically commit the updated CSV file back to the repository.
      - name: Commit new data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Data: Add latest solar radiation data"
          file_pattern: 'solar_data.csv'
